version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all" ]

  app:
    build:
      context: .
    user: "evs:grp"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - "MIGRATIONS_PATH:${MIGRATIONS}"
      - "POSTGRES_USER:${POSTGRES_USER}"
      - "POSTGRES_PASSWORD:${POSTGRES_PASSWORD}"
      - "POSTGRES_DB:${POSTGRES_DB}"
      - "POSTGRES_PORT:${POSTGRES_PORT}"
    volumes:
      - "./${MIGRATIONS}:/app/${MIGRATIONS}"
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"