BEGIN;

CREATE TABLE IF NOT EXISTS banners (
		id INTEGER PRIMARY KEY ,
		tag_ids INTEGER NOT NULL,
		feature_id INTEGER NOT NULL,
		content JSON NOT NULL,
		is_active BOOLEAN DEFAULT TRUE,
		created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	);

CREATE TABLE IF NOT EXISTS user (
		id INTEGER PRIMARY KEY ,
		is_admin BOOLEAN NOT NULL DEFAULT FALSE,
	);

COMMIT;