env: "local"
storage_path: "./storage/storage.db"

jwt_key : "wellcometoavitofamily"

http_server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 30s

postgesql:
  POSTGRES_USER : "novitiate"
  POSTGRES_PASSWORD : "1234"
  POSTGRES_DB : "banners"
  POSTGRES_PORT : 4455
  MIGRATIONS : "migrations"

